defaults:
  - _self_

project_name: "phobert-uit-vsfc"
seed: 42
run_name: "phobert_vsfc_regularization"

paths:
  ckpt_dir: "checkpoints/"
  log_dir: "logs/"

data: 
  data_dir: "./data/processed" # thư mục chứa train.csv, dev.csv, test.csv
  batch_size: 32
  max_len: 128
  num_workers: 4

model:
  model_name: "vinai/phobert-large"
  num_labels: 4
  learning_rate: 2e-5
  class_names: ["Lecturer", "Curriculum", "Facility", "Others"] # Thêm dòng này
  weight_decay: 0.05 # Thường dùng cho BERT
  dropout: 0.3

trainer:
  max_epochs: 10
  accelerator: "gpu"
  devices: 1

logger:
  wandb:
    project: "phobert-uit-vsfc" # Tên project trên web
    log_model: True # Tự động upload checkpoint lần cloud